ci:
  autofix_prs: false
  autoupdate_schedule: weekly
  autoupdate_commit_msg: 'chore(deps): pre-commit autoupdate'
  skip:
  - check-dependabot

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-json
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.29.0
  hooks:
  - id: check-dependabot
  - id: check-github-workflows
  - id: check-readthedocs

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.5.4
  hooks:
  - id: ruff
    args: [--fix, --exit-non-zero-on-fix, --show-fixes]
  - id: ruff-format

- repo: https://github.com/pycqa/flake8
  rev: 7.1.0
  hooks:
  - id: flake8
    additional_dependencies:
    - darglint==1.8.1

- repo: https://github.com/pre-commit/pre-commit
  rev: v3.7.1
  hooks:
  - id: validate_manifest

- repo: https://github.com/tox-dev/pyproject-fmt
  rev: "2.1.4"
  hooks:
  - id: pyproject-fmt
